# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring.config.activate.on-profile: monday
words: помірна, 25%, Kp-4, стабільна, без CME

---
spring.config.activate.on-profile: tuesday
words: висока, 60%, Kp-6, активна, очікується CME

---
spring.config.activate.on-profile: wednesday
words: низька, 10%, Kp-3, зменшення, без CME

---
spring.config.activate.on-profile: thursday
words: помірна, 30%, Kp-5, нова область, CME під спостереженням
