---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/


---
spring.config.activate.on-profile: subject
words: test1, test2
  
---
spring.config.activate.on-profile: verb
words: test3, test4

---
spring.config.activate.on-profile: article
words: test5,test6

---
spring.config.activate.on-profile: adjective
words: test7,test8

---
spring.config.activate.on-profile: noun
words: test9,test10
